### PR TITLE
Add missing "interactive" forms

### PR DESCRIPTION
**Pull request by alezost**
I suppose those should be interactive commands, no?

And thanks for such a powerful package!

### CODE REVIEW

**Comment by momomo5717** [comment]
Thanks PR and reviewing!

I suppose emms-player-simple-mpv-mute-on/off are used for emms-pause/resume insted of emms-player-simple-mpv-pause/unpause when mpv cannot use pause/unpause for some streaming URLs.

**Comment by momomo5717** [comment]
Hi.

I'm in thinking about that.

I suppose that some users might think it looks like redundant
because `M-x helm-M-x RET mpv mute` displays three mute functions  and
`emms-player-simple-mpv-mute` includes the action.

Therefore, I think that non interactive is better now.

What do you think about?

I apologize in advance if my English was unclear or if I have written something rude due to my English grammatical problem or skill.

Thanks!

**Comment by alezost** [comment]
No need to apologize (my English is also not perfect :smile:).  And
sure, you are right that it may be confusing to a user.  I just
mistakenly thought that originally you wanted to make those functions
interactive and just forgot to do it.  So I'm closing this PR.

**Comment by momomo5717** [comment]
Thanks for your kindness. Until next time!

**Pull request closed without merging**
